version: '3'
services:
  app:
    build: .
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    ports:
      - '33061:3306'
    volumes:
      - './db-scripts/:/docker-entrypoint-initdb.d'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'